### ISSUE TITLE
NPM install module does not work

### ISSUE THREAD

**Issue by scottwestover** [scottwestover/Unofficial-LiveEngage-API-Wrapper#6]
When you try to install the module, you get an error. Here is the error:

Error: Cannot find module '/lib/Credentials'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/le-api/index.js:3:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by scottwestover** [comment]
This issue has been resolved, and you can use the module as normal. This was fixed in v0.3.1, commit - [9376181614d35fb29060c72d3582387a35d72240](https://github.com/scottwestover/Unofficial-LiveEngage-API-Wrapper/commit/9376181614d35fb29060c72d3582387a35d72240)
